In [1]:
# Import libraries
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
# Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]


In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Vocabulary size
voc_size = 10000

In [5]:
# One-hot encoding
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print("One-hot representation:\n", one_hot_repr)

One-hot representation:
 [[1135, 1519, 3357, 5828], [1135, 1519, 3357, 6228], [1135, 9819, 3357, 2406], [2142, 4815, 8153, 9273, 4050], [2142, 4815, 8153, 9273, 4139], [1187, 1135, 1263, 3357, 6223], [8360, 8371, 1000, 9273]]


In [6]:
# Padding
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print("\nPadded sequences:\n", embedded_docs)



Padded sequences:
 [[   0    0    0    0 1135 1519 3357 5828]
 [   0    0    0    0 1135 1519 3357 6228]
 [   0    0    0    0 1135 9819 3357 2406]
 [   0    0    0 2142 4815 8153 9273 4050]
 [   0    0    0 2142 4815 8153 9273 4139]
 [   0    0    0 1187 1135 1263 3357 6223]
 [   0    0    0    0 8360 8371 1000 9273]]


In [7]:
# Embedding model
dim = 10


In [8]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile(optimizer='adam', loss='mse')

c:\Users\jenis\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
# Get embeddings
output = model.predict(embedded_docs)
print("\nEmbedding output shape:", output.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

Embedding output shape: (7, 8, 10)
