# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np
import random
arr1 = np.random.randint(1,21, size=(5,5))
print(f'Array before modification: \n{arr1}\n')

arr1[:, 2] = 1
print(f'Array after modification: \n{arr1}')


Array before modification: 
[[ 7  2  9  8 16]
 [ 2 14  7 14  2]
 [ 7 11 12 15 13]
 [13 12 13 14 12]
 [ 7 13 17 16 10]]

Array after modification: 
[[ 7  2  1  8 16]
 [ 2 14  1 14  2]
 [ 7 11  1 15 13]
 [13 12  1 14 12]
 [ 7 13  1 16 10]]


In [14]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2 = np.random.randint(1, 17, size=(4,4))
print(f'Array before modification : \n{arr2}\n')
np.fill_diagonal(arr2, 0)
print(f'Array after modification: \n{arr2}')

Array before modification : 
[[16  2  4 11]
 [ 7 10 16  7]
 [ 2 11  3  3]
 [ 3 13 12  8]]

Array after modification: 
[[ 0  2  4 11]
 [ 7  0 16  7]
 [ 2 11  0  3]
 [ 3 13 12  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [31]:
# 1
arr3 = np.random.randint(1, 37, size=(6,6))
print(f'Original Array: \n{arr3}\n')
sub_arr3 = arr3[3:6, 2:5]
print(f'Sub array: \n{sub_arr3}')

Original Array: 
[[12 28 30 23 28  3]
 [33  4  3 15 35 20]
 [26 21 33 11 19 10]
 [31 19 21 23 13  9]
 [24 14 13 11 28 16]
 [27 36 16  5 18 20]]

Sub array: 
[[21 23 13]
 [13 11 28]
 [16  5 18]]


In [32]:
# 2 
arr4 = np.random.randint(1, 50, size=(5,5))
print(f'Original Array: \n{arr4}\n')

top = arr4[0, :]
bottom = arr4[-1, :]
left = arr4[1:-1, 0]
right = arr4[1:-1, -1]

border_elements = np.concatenate([top, right, bottom[::-1], left[::-1]])

print("\nBorder elements:")
print(border_elements)


Original Array: 
[[22 32  4 48  4]
 [23 12 23 42 44]
 [49 10 47 24 41]
 [14 46  4 16 18]
 [23 44 42 38 33]]


Border elements:
[22 32  4 48  4 44 41 18 33 38 42 44 23 14 49 23]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.


In [30]:
#1
arr5_a = np.random.randint(1,50 , size=(3,4))
arr5_b = np.random.randint(1,50, size=(3,4))
print(f'Array A: \n{arr5_a}\n')
print(f'Array B: \n{arr5_b}\n')

sum_arr5 = arr5_a + arr5_b
print(f'Element wise sum of two arrays: \n{sum_arr5}\n')

diff_arr5 = arr5_a - arr5_b
print(f'Element wise difference of two arrays: \n{diff_arr5}\n')

mul_arr5 = arr5_a * arr5_b
print(f'Element wise multiplication of two arrays: \n{mul_arr5}\n')

div_arr5 = arr5_a // arr5_b
print(f'Element wise division of two arrays: \n{div_arr5}\n')

Array A: 
[[13 12  5 40]
 [34  5 21 10]
 [ 7 26 13 16]]

Array B: 
[[43 14 33 41]
 [15 37  4 31]
 [35 13 46 29]]

Element wise sum of two arrays: 
[[56 26 38 81]
 [49 42 25 41]
 [42 39 59 45]]

Element wise difference of two arrays: 
[[-30  -2 -28  -1]
 [ 19 -32  17 -21]
 [-28  13 -33 -13]]

Element wise multiplication of two arrays: 
[[ 559  168  165 1640]
 [ 510  185   84  310]
 [ 245  338  598  464]]

Element wise division of two arrays: 
[[0 0 0 0]
 [2 0 5 0]
 [0 2 0 0]]



In [34]:
#2 
arr6 = np.random.randint(1, 17, size=(4,4))
print(f'Original Array: \n{arr6}\n')

row_sum = np.sum(arr6, axis = 1)
col_sum = np.sum(arr6, axis = 0)
print(f'Sum of each row: \n{row_sum}\n')
print(f'Sum of each column: \n{col_sum}\n')

Original Array: 
[[ 2 13  9 16]
 [ 2  7 15  9]
 [12 16  7  9]
 [ 5  1  1  3]]

Sum of each row: 
[40 33 44 10]

Sum of each column: 
[21 37 32 37]



### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [35]:
# 1
arr7 = np.random.randint(1, 50, size=(5,5))
print(f'Original Array: \n{arr7}\n')
print(f'Mean: {np.mean(arr7)}')
print(f'Median: {np.median(arr7)}')
print(f'Standard Deviation: {np.std(arr7)}')
print(f'Variance: {np.var(arr7)}')


Original Array: 
[[16 45  5 35 18]
 [19 19 41 43 30]
 [34 30 38 49 46]
 [43 13 48 33 10]
 [ 3 20 19 14 27]]

Mean: 27.92
Median: 30.0
Standard Deviation: 13.772203890445422
Variance: 189.6736


In [41]:
# 2
arr8 = np.random.randint(1, 10, size=(3,3))
print(f'Original Array: \n{arr8}\n')
mean_arr8 = np.mean(arr8)
std_arr8 = np.std(arr8)
normalized_arr8 = (arr8 - mean_arr8) / std_arr8
print(f'Normalized Array: \n{normalized_arr8}\n')

Original Array: 
[[1 7 9]
 [3 7 3]
 [3 8 8]]

Normalized Array: 
[[-1.61426862  0.56499402  1.2914149 ]
 [-0.88784774  0.56499402 -0.88784774]
 [-0.88784774  0.92820446  0.92820446]]



### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
# 1
arr9 = np.random.randint(1, 26, size=(3,3))
print(f'Original Array: \n{arr9}\n')

row_add = np.array([1, 2, 3])
result = arr9 + row_add

print("\nAfter adding to each row:\n", result)

Original array:
[[ 4 10  1]
 [ 5  8  5]
 [ 8  3  3]]
1D array:
[1 8 4]
Resulting array:
[[ 5 18  5]
 [ 6 16  9]
 [ 9 11  7]]


In [45]:
# 3
arr10 = np.random.randint(1, 26, size=(3,3))
print(f'Original Array: \n{arr10}\n')

col_add = np.array([1, 2, 4])
result = arr10 + col_add

print("\nAfter adding to each column:\n", result)

Original Array: 
[[ 9  7 23]
 [10 12  2]
 [ 8 21 12]]


After adding to each column:
 [[10  9 27]
 [11 14  6]
 [ 9 23 16]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [3]:

arr11 = np.random.randint(1, 26, size=(3,3))
print(f"Original matrix:\n{arr11}\n")

determinant = np.linalg.det(arr11)
print(f"Determinant:\n{determinant}\n")

inverse = np.linalg.inv(arr11)
print(f"Inverse:\n{inverse}\n")

eigenvalues = np.linalg.eigvals(arr11)
print(f"Eigenvalues:\n{eigenvalues}")

Original matrix:
[[13 12 21]
 [ 9  6  8]
 [ 8 24 20]]

Determinant:
1200.0

Inverse:
[[-0.06        0.22       -0.025     ]
 [-0.09666667  0.07666667  0.07083333]
 [ 0.14       -0.18       -0.025     ]]

Eigenvalues:
[40. +0.j         -0.5+5.45435606j -0.5-5.45435606j]


In [7]:
arr12_a = np.random.randint(1, 26, size=(2,3))
arr12_b = np.random.randint(1, 26, size=(3,2))
print(f"Original matrices are:\n{arr12_a}\n{arr12_b}\n")

arr12_c = np.dot(arr12_a, arr12_b)
print(f"Multiplication result:\n{arr12_c}")

Original matrices are:
[[ 6  8  9]
 [ 9 18 23]]
[[20 11]
 [19 15]
 [13 23]]

Multiplication result:
[[389 393]
 [821 898]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [8]:
# 1
arr13 = np.random.randint(1, 10, size=(3,3))
print(f"Original matrix:\n{arr13}\n")

reshaped1 = arr13.reshape((1,9))
print(f"Reshaped: \n{reshaped1}\n")

reshaped2 = arr13.reshape((9,1))
print(f"Reshaped: \n{reshaped2}\n")

Original matrix:
[[4 4 1]
 [7 5 1]
 [6 2 7]]

Reshaped: 
[[4 4 1 7 5 1 6 2 7]]

Reshaped: 
[[4]
 [4]
 [1]
 [7]
 [5]
 [1]
 [6]
 [2]
 [7]]



In [11]:
arr14 = np.random.randint(1, 26, size=(5,5))
print(f"Original matrix:\n{arr14}\n")

flattened = arr14.flatten()
print(f"Flattened array:\n{flattened}\n")

reshape1 = flattened.reshape((5,5))
print(f"Reshaped array: \n{reshape1}")

Original matrix:
[[16  3  3 13 10]
 [ 2  1 25  1 18]
 [22 21 16  6 11]
 [20 18 20  8 20]
 [ 1 17  4 13  6]]

Flattened array:
[16  3  3 13 10  2  1 25  1 18 22 21 16  6 11 20 18 20  8 20  1 17  4 13
  6]

Reshaped array: 
[[16  3  3 13 10]
 [ 2  1 25  1 18]
 [22 21 16  6 11]
 [20 18 20  8 20]
 [ 1 17  4 13  6]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [12]:
arr15 = np.random.randint(1, 26, size=(5,5))
print(f"Original matrix:\n{arr15}\n")
corners = arr15[[0, 0, -1, -1], [0, -1, 0, -1]]
print(f"Corner elements:\n{corners}")

Original matrix:
[[ 8 11  6  1  8]
 [ 1 21 21  2 11]
 [ 5 25 16 19 21]
 [ 7  4  4  1 18]
 [21 22 16 17  5]]

Corner elements:
[ 8  8 21  5]


In [13]:
arr16 = np.random.randint(1, 26, size=(4,4))
print(f"Original matrix:\n{arr15}\n")

arr16[arr16 > 10] = 10
print(f"Modified array:\n{arr16}")

Original matrix:
[[ 8 11  6  1  8]
 [ 1 21 21  2 11]
 [ 5 25 16 19 21]
 [ 7  4  4  1 18]
 [21 22 16 17  5]]

Modified array:
[[10  6 10 10]
 [10 10 10 10]
 [ 2 10 10  7]
 [10  2 10 10]]
